services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npx", "nodemon", "--watch", ".", "src/server.ts"]
